# Ansible Inventory
# =============================================================================

# General host categories
# -----------------------------------------------------------------------------
[vms]
microservice-host ansible_host=192.168.1.13 ansible_user=ubuntu
game-server     ansible_host=192.168.1.16 ansible_user=debian

[lxc]
vpn-gateway       ansible_host=192.168.1.14 ansible_user=root
cloudflare-tunnel ansible_host=192.168.1.15 ansible_user=root


# Playbook-specific groups
# -----------------------------------------------------------------------------
[microservice_vm]
microservice-host

[tailscale_lxc]
vpn-gateway

[cloudflare_lxc]
cloudflare-tunnel

[game_server]
game-server

# Meta-group containing all hosts
# -----------------------------------------------------------------------------
[all:children]
vms
lxc
