---
- name: Install Playit Agent
  hosts: playit_client
  become: true

  tasks:
    - name: Install basic dependencies
      ansible.builtin.apt:
        name: [curl, gnupg, ca-certificates]
        state: present
        update_cache: true

    - name: Add Playit.gg Repository
      ansible.builtin.shell:
        cmd: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor -o /usr/share/keyrings/playit-keyring.gpg --yes
          echo "deb [signed-by=/usr/share/keyrings/playit-keyring.gpg] https://playit-cloud.github.io/ppa/data ./" > /etc/apt/sources.list.d/playit-official.list
          apt-get update
      args:
        creates: /etc/apt/sources.list.d/playit-official.list

    - name: Install playit package
      ansible.builtin.apt:
        name: playit
        state: present