---
- name: Run all playbooks
  hosts: all

- name: Import Docker Installation Playbook
  import_playbook: install_docker.yml

- name: Import Tailscale Sentry Playbook
  import_playbook: deploy_tailscale.yml

- name: Import Portainer Management Playbook
  import_playbook: deploy_portainer.yml
